name: Test Case - Java Spring App

on:
  push:
  workflow_dispatch:

env:
  NIGHTVISION_TOKEN: ${{ secrets.NIGHTVISION_TOKEN }}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: (1) Clone Code
        uses: actions/checkout@v3
      
      - name: (2) Install NightVision
        run: make install-cli

      - name: (3) Run API Envy
        run: nightvision extract-api-docs ./ -u https://localhost:9000

      - name: (4) Start app
        run: docker-compose up -d; sleep 10

      - name: (5) Scan the API
        run: nightvision scan https://localhost:9000
